// Template Registry — all built-in letter templates

/** @type {import('../registry').LetterTypeDefinition[]} */
const templates = [
  {
    id: 'event-hosting-request',
    displayName: 'Event Hosting Request',
    template: [
      'Dear Administrator,',
      '',
      'I am writing on behalf of {{organization_name}} to formally request permission to host an event at {{institution_name}}.',
      '',
      'Event Details:',
      '- Event Name: {{event_name}}',
      '- Facility Requested: {{facility_name}}',
      '- Date: {{event_date}}',
      '- Time: {{event_time}}',
      '- Expected Participants: {{expected_participants}}',
      '',
      'Event Description:',
      '{{event_description}}',
      '',
      'We believe this event aligns with the values and mission of {{institution_name}}, and we are committed to ensuring the facility is treated with the utmost care throughout its use.',
      '',
      'Additional Requests or Special Considerations:',
      '{{additional_requests}}',
      '',
      'Should you require any further information, please contact us at {{contact_info}}.',
      '',
      'Thank you for your time and consideration. We look forward to your favorable response.',
      '',
      'Sincerely,',
      '',
      '{{organizer_name}}',
      '{{organization_name}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'institution_name', label: 'Institution Name', required: true },
      { key: 'facility_name', label: 'Facility Name', required: true },
      { key: 'event_name', label: 'Event Name', required: true },
      { key: 'event_description', label: 'Event Description', required: true },
      { key: 'event_date', label: 'Event Date', required: true },
      { key: 'event_time', label: 'Event Time', required: true },
      { key: 'expected_participants', label: 'Expected Participants', required: true },
      { key: 'organizer_name', label: 'Organizer Name', required: true },
      { key: 'organization_name', label: 'Organization Name', required: true },
      { key: 'contact_info', label: 'Contact Info', required: true },
      { key: 'additional_requests', label: 'Additional Specific Requests', required: true },
    ],
  },
  {
    id: 'support-request-letter',
    displayName: 'Support Request Letter',
    template: [
      'Dear Support Team,',
      '',
      'I am writing on behalf of {{organization_name}} to respectfully request support from {{institution_name}} for an initiative we are currently undertaking.',
      '',
      'Project/Initiative: {{project_name}}',
      '',
      'Project Description:',
      '{{project_description}}',
      '',
      'Support Requested:',
      '- Type of Support: {{support_type}}',
      '- Resources Needed: {{resources_needed}}',
      '',
      'We believe that with the support of {{institution_name}}, this project will have a meaningful and lasting impact on our community.',
      '',
      'Please feel free to contact us at {{contact_info}} to discuss this further.',
      '',
      'Thank you for considering our request.',
      '',
      'Sincerely,',
      '',
      '{{organizer_name}}',
      '{{organization_name}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'institution_name', label: 'Institution Name', required: true },
      { key: 'project_name', label: 'Project / Event Name', required: true },
      { key: 'project_description', label: 'Project Description', required: true },
      { key: 'support_type', label: 'Support Type', required: true },
      { key: 'resources_needed', label: 'Resources Needed', required: true },
      { key: 'organizer_name', label: 'Organizer Name', required: true },
      { key: 'organization_name', label: 'Organization Name', required: true },
      { key: 'contact_info', label: 'Contact Info', required: true },
    ],
  },
  {
    id: 'resignation-letter',
    displayName: 'Resignation Letter',
    template: [
      'Dear {{manager_name}},',
      '',
      'I am writing to formally notify you of my resignation from my position as {{job_title}} at {{company_name}}, effective {{last_working_day}}.',
      '',
      'This was not an easy decision. I have genuinely valued my time at {{company_name}} and am grateful for the opportunities and professional growth I have gained during my tenure.',
      '',
      'Reason for Resignation:',
      '{{reason_for_leaving}}',
      '',
      'I am committed to ensuring a smooth transition and am happy to assist in training my replacement before my last day.',
      '',
      'Thank you for your support and guidance throughout my time here.',
      '',
      'Sincerely,',
      '',
      '{{your_name}}',
      '{{job_title}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'manager_name', label: 'Manager / Recipient Name', required: true },
      { key: 'job_title', label: 'Your Job Title', required: true },
      { key: 'company_name', label: 'Company Name', required: true },
      { key: 'last_working_day', label: 'Last Working Day', required: true },
      { key: 'reason_for_leaving', label: 'Reason for Leaving', required: true },
      { key: 'your_name', label: 'Your Full Name', required: true },
      { key: 'contact_info', label: 'Contact Info', required: true },
    ],
  },
  {
    id: 'recommendation-letter',
    displayName: 'Recommendation Letter',
    template: [
      'Dear {{recipient_name}},',
      '',
      'I am pleased to write this letter of recommendation for {{candidate_name}}, whom I have had the privilege of knowing as {{your_relationship}} at {{your_organization}}.',
      '',
      'During the period of {{duration}}, {{candidate_name}} consistently demonstrated exceptional qualities.',
      '',
      'Key Strengths and Achievements:',
      '{{key_strengths}}',
      '',
      'I am confident that {{candidate_name}} will bring the same dedication and excellence to {{position_applied_for}}. I recommend them without reservation.',
      '',
      'Please feel free to contact me at {{your_contact}} for further information.',
      '',
      'Sincerely,',
      '',
      '{{your_name}}',
      '{{your_title}}',
      '{{your_organization}}',
      '{{your_contact}}',
    ].join('\n'),
    fields: [
      { key: 'recipient_name', label: 'Recipient Name', required: true },
      { key: 'candidate_name', label: 'Candidate Full Name', required: true },
      { key: 'your_relationship', label: 'Your Relationship to Candidate', required: true },
      { key: 'your_organization', label: 'Your Organization', required: true },
      { key: 'duration', label: 'Duration Known (e.g. 2 years)', required: true },
      { key: 'key_strengths', label: 'Key Strengths & Achievements', required: true },
      { key: 'position_applied_for', label: 'Position Applied For', required: true },
      { key: 'your_name', label: 'Your Full Name', required: true },
      { key: 'your_title', label: 'Your Title / Position', required: true },
      { key: 'your_contact', label: 'Your Contact Info', required: true },
    ],
  },
  {
    id: 'complaint-letter',
    displayName: 'Complaint Letter',
    template: [
      'Dear {{recipient_name}},',
      '',
      'I am writing to formally express my concern regarding {{complaint_subject}} at {{company_or_institution}}.',
      '',
      'Details of the Complaint:',
      '{{complaint_details}}',
      '',
      'Date of Incident: {{incident_date}}',
      '',
      'This issue has caused {{impact_description}}. I have previously attempted to resolve this by {{previous_attempts}}, but the issue remains unresolved.',
      '',
      'I respectfully request that {{requested_resolution}} be addressed at the earliest convenience.',
      '',
      'Please contact me at {{contact_info}} to discuss further.',
      '',
      'Sincerely,',
      '',
      '{{your_name}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'recipient_name', label: 'Recipient Name / Department', required: true },
      { key: 'complaint_subject', label: 'Subject of Complaint', required: true },
      { key: 'company_or_institution', label: 'Company / Institution Name', required: true },
      { key: 'complaint_details', label: 'Complaint Details', required: true },
      { key: 'incident_date', label: 'Date of Incident', required: true },
      { key: 'impact_description', label: 'Impact / How It Affected You', required: true },
      { key: 'previous_attempts', label: 'Previous Attempts to Resolve', required: true },
      { key: 'requested_resolution', label: 'Requested Resolution', required: true },
      { key: 'your_name', label: 'Your Full Name', required: true },
      { key: 'contact_info', label: 'Your Contact Info', required: true },
    ],
  },
  {
    id: 'job-application-letter',
    displayName: 'Job Application Letter',
    template: [
      'Dear {{hiring_manager_name}},',
      '',
      'I am writing to express my strong interest in the {{position_title}} position at {{company_name}}, as advertised on {{job_source}}.',
      '',
      'About Me:',
      '{{about_yourself}}',
      '',
      'Relevant Experience and Skills:',
      '{{relevant_experience}}',
      '',
      'Why {{company_name}}:',
      '{{why_this_company}}',
      '',
      'I am excited about the opportunity to contribute to {{company_name}} and am confident that my background makes me a strong candidate. I have attached my resume and would welcome the opportunity to discuss my application further.',
      '',
      'Thank you for your time and consideration.',
      '',
      'Sincerely,',
      '',
      '{{your_name}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'hiring_manager_name', label: 'Hiring Manager Name', required: true },
      { key: 'position_title', label: 'Position Title', required: true },
      { key: 'company_name', label: 'Company Name', required: true },
      { key: 'job_source', label: 'Where You Found the Job', required: true },
      { key: 'about_yourself', label: 'Brief Introduction About Yourself', required: true },
      { key: 'relevant_experience', label: 'Relevant Experience & Skills', required: true },
      { key: 'why_this_company', label: 'Why You Want to Work Here', required: true },
      { key: 'your_name', label: 'Your Full Name', required: true },
      { key: 'contact_info', label: 'Your Contact Info', required: true },
    ],
  },
];

module.exports = templates;
