// Template Registry entries — enhanced with formatting and consistency

/** @type {import('../registry').LetterTypeDefinition[]} */
const templates = [
  {
    id: 'event-hosting-request',
    displayName: 'Event Hosting Request',
    template: [
      'Dear Administrator,',
      '',
      'I am writing on behalf of **{{organization_name}}** to formally request permission to host an event at **{{institution_name}}**.',
      '',
      '**Event Details**',
      '',
      '- **Event Name:** {{event_name}}',
      '- **Facility Requested:** {{facility_name}}',
      '- **Date:** {{event_date}}',
      '- **Time:** {{event_time}}',
      '- **Expected Participants:** {{expected_participants}}',
      '',
      '**Event Description**',
      '{{event_description}}',
      '',
      'We believe this event aligns with the values and mission of **{{institution_name}}**, and we are committed to ensuring that the facility is treated with the utmost care and respect throughout its use.',
      '',
      '**Additional Requests or Special Considerations**',
      '{{additional_requests}}',
      '',
      'Should you require any further information or wish to discuss this request, please do not hesitate to contact us at **{{contact_info}}**.',
      '',
      'Thank you for your time and consideration. We look forward to your favorable response.',
      '',
      'Sincerely,',
      '',
      '**{{organizer_name}}**',
      '{{organization_name}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'institution_name', label: 'Institution Name', required: true },
      { key: 'facility_name', label: 'Facility Name', required: true },
      { key: 'event_name', label: 'Event Name', required: true },
      { key: 'event_description', label: 'Event Description', required: true },
      { key: 'event_date', label: 'Event Date', required: true },
      { key: 'event_time', label: 'Event Time', required: true },
      { key: 'expected_participants', label: 'Expected Participants', required: true },
      { key: 'organizer_name', label: 'Organizer Name', required: true },
      { key: 'organization_name', label: 'Organization Name', required: true },
      { key: 'contact_info', label: 'Contact Info', required: true },
      { key: 'additional_requests', label: 'Additional Specific Requests', required: true },
    ],
  },

  {
    id: 'support-request-letter',
    displayName: 'Support Request Letter',
    template: [
      'Dear Support Team,',
      '',
      'I am writing on behalf of **{{organization_name}}** to respectfully request support from **{{institution_name}}** for an initiative we are currently undertaking.',
      '',
      '**Project Information**',
      '',
      '- **Project/Initiative:** {{project_name}}',
      '',
      '**Project Description**',
      '{{project_description}}',
      '',
      '**Support Requested**',
      '',
      '- **Type of Support:** {{support_type}}',
      '- **Resources Needed:** {{resources_needed}}',
      '',
      'We believe that with the support of **{{institution_name}}**, this project will have a meaningful and lasting impact on our community. Our organization is committed to the responsible and transparent use of any resources provided, and we are prepared to submit progress updates or reports as required.',
      '',
      'We would welcome the opportunity to discuss this request further at your convenience. Please feel free to contact us at **{{contact_info}}**.',
      '',
      'Thank you for considering our request. We sincerely appreciate your time and the work that **{{institution_name}}** does in supporting initiatives like ours.',
      '',
      'Sincerely,',
      '',
      '**{{organizer_name}}**',
      '{{organization_name}}',
      '{{contact_info}}',
    ].join('\n'),
    fields: [
      { key: 'institution_name', label: 'Institution Name', required: true },
      { key: 'project_name', label: 'Project / Event Name', required: true },
      { key: 'project_description', label: 'Project Description', required: true },
      { key: 'support_type', label: 'Support Type', required: true },
      { key: 'resources_needed', label: 'Resources Needed', required: true },
      { key: 'organizer_name', label: 'Organizer Name', required: true },
      { key: 'organization_name', label: 'Organization Name', required: true },
      { key: 'contact_info', label: 'Contact Info', required: true },
    ],
  },
];

module.exports = templates;